package com.gdpr.controller;

public class GdprConstant {
	

	/*public static String DROP_GDPR_DELETION_REPORT_TABLE = " BEGIN EXECUTE IMMEDIATE 'DROP TABLE GDPR_DELETION_REPORT_TEST';"
			+ " EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE;"
			+ " END IF;"
			+ " END;";*/
	public static String DROP_GDPR_DELETION_REPORT_TABLE = "DROP TABLE GDPR_DELETION_REPORT";
	
	public static String CREATE_GDPR_DELETION_REPORT_TABLE = "CREATE TABLE GDPR_DELETION_REPORT("+"REQUEST_ID NUMBER,MODULE_ID VARCHAR2(50 BYTE),RECORD_ID VARCHAR2(50 BYTE),"
			+ "DISPLAY_ID VARCHAR2(1000 BYTE),DATE_TOBE_CONSIDERED DATE,EXPECTED_DEL_DATE DATE,DEL_EXEC_DATE DATE, DATA_HOLD VARCHAR2(1 BYTE),"
			+ "MAPPED_DATA_HOLD VARCHAR2(500 BYTE),MAX_DATA_HOLD_DATE DATE, SOFT_DELETE VARCHAR2(1 BYTE), STATUS VARCHAR2(100 BYTE),"
			+ "REASON VARCHAR2(1000 BYTE), DELETE_FAILURE_REASON VARCHAR2(1000 BYTE))";
	
	public static String DROP_GDPR_PRE_DELETION_REPORT_TABLE = "DROP TABLE GDPR_PRE_DELETION_REPORT";
	
	public static String CREATE_GDPR_PRE_DELETION_REPORT_TABLE = "CREATE TABLE GDPR_PRE_DELETION_REPORT("+"REQUEST_ID NUMBER,MODULE_ID VARCHAR2(50 BYTE),RECORD_ID VARCHAR2(50 BYTE),"
			+ "DISPLAY_ID VARCHAR2(1000 BYTE),DATE_TOBE_CONSIDERED DATE,EXPECTED_DEL_DATE DATE,DEL_EXEC_DATE DATE, DATA_HOLD VARCHAR2(1 BYTE),"
			+ "MAPPED_DATA_HOLD VARCHAR2(500 BYTE),MAX_DATA_HOLD_DATE DATE, SOFT_DELETE VARCHAR2(1 BYTE), STATUS VARCHAR2(100 BYTE),"
			+ "REASON VARCHAR2(1000 BYTE))";
	
	public static final String DROP_GDPR_DELETION_APPROVE_REPORT_TABLE = "DROP TABLE GDPR_DELETION_APPROVE_REPORT";

	public static final String CREATE_GDPR_DELETION_APPROVE_REPORT_TABLE = "CREATE TABLE GDPR_DELETION_APPROVE_REPORT("+"REQUEST_ID NUMBER,MODULE_ID VARCHAR2(50 BYTE),RECORD_ID VARCHAR2(50 BYTE),"
			+ "DISPLAY_ID VARCHAR2(1000 BYTE),DATE_TOBE_CONSIDERED DATE,EXPECTED_DEL_DATE DATE,DEL_EXEC_DATE DATE, DATA_HOLD VARCHAR2(1 BYTE),"
			+ "MAPPED_DATA_HOLD VARCHAR2(500 BYTE),MAX_DATA_HOLD_DATE DATE, SOFT_DELETE VARCHAR2(1 BYTE), STATUS VARCHAR2(100 BYTE),"
			+ "REASON VARCHAR2(1000 BYTE), APPROVAL DATE)";

	public static final String DROP_GDPR_PRE_DELETION_WF_MSTR_TABLE = "DROP TABLE GDPR_PRE_DELETION_WF_MSTR";

	public static final String CREATE_GDPR_PRE_DELETION_WF_MSTR_TABLE = "CREATE TABLE GDPR_PRE_DELETION_WF_MSTR("+"REQUEST_ID NUMBER,REPORT_DATE DATE,CREATED_BY VARCHAR2(100 BYTE),"
			+ "CREATED_DATE DATE,MODIFIED_BY VARCHAR2(100 BYTE),MODIFIED_DATE DATE,LAST_MAKER VARCHAR2(100 BYTE), LAST_CHECKER VARCHAR2(100 BYTE),"
			+ "STATUS_COMMENT VARCHAR2(1000 BYTE),WF_STATUS VARCHAR2(1000 BYTE))";

	public static final String DROP_GDPR_DATA_HOLD_MSTR_TABLE = "DROP TABLE GDPR_DATA_HOLD_MSTR";

	public static final String CREATE_GDPR_DATA_HOLD_MSTR_TABLE = "CREATE TABLE GDPR_DATA_HOLD_MSTR("+"ID VARCHAR2(100 BYTE),EXTERNAL_DATA_HOLD_ID VARCHAR2(1000 BYTE),HOLD_TYPE VARCHAR2(10 BYTE),"
			+ "HOLD_START_DATE DATE,HOLD_END_DATE DATE,COMMENTS VARCHAR2(4000 BYTE),CREATED_BY VARCHAR2(100 BYTE), CREATED_DATE DATE,"
			+ "MODIFIED_BY VARCHAR2(100 BYTE),MODIFIED_DATE DATE,LAST_MAKER VARCHAR2(100 BYTE), LAST_CHECKER VARCHAR2(100 BYTE), STATUS_COMMENT VARCHAR2(1000 BYTE), WF_STATUS VARCHAR2(1000 BYTE))";

	public static final String DROP_GDPR_DATA_HOLD_MAPPING_MSTR_TABLE = "DROP TABLE GDPR_DATA_HOLD_MAPPING_MSTR";

	public static final String CREATE_GDPR_DATA_HOLD_MAPPING_MSTR_TABLE = "CREATE TABLE GDPR_DATA_HOLD_MAPPING_MSTR("+"ID VARCHAR2(100 BYTE),DATA_HOLD_ID VARCHAR2(30 BYTE),RECORD_ID VARCHAR2(50 BYTE),"
			+ "DISPLAY_ID VARCHAR2(500 BYTE),MODULE_ID VARCHAR2(30 BYTE),ACTIVE_STATUS VARCHAR2(100 BYTE),CREATED_DATE DATE, MODIFIED_BY VARCHAR2(100 BYTE),"
			+ "MODIFIED_DATE DATE,LAST_MAKER VARCHAR2(100 BYTE), LAST_CHECKER VARCHAR2(100 BYTE), STATUS_COMMENT VARCHAR2(1000 BYTE), WF_STATUS VARCHAR2(1000 BYTE))";

	public static final String DROP_GDPR_MODULE_CONFIG_TABLE = "DROP TABLE GDPR_MODULE_CONFIG";

	public static final String CREATE_GDPR_MODULE_CONFIG_TABLE = "CREATE TABLE GDPR_MODULE_CONFIG("+"MODULE_ID VARCHAR2(100 BYTE),QUERY_TYPE VARCHAR2(50 BYTE),MODULE_BASE_QUERY VARCHAR2(4000 BYTE),"
			+ "VALIDATION_PROC VARCHAR2(400 BYTE),DELETION_PROC VARCHAR2(400 BYTE),BASE_QUERY_VIEW VARCHAR2(4000 BYTE),CREATED_DATE DATE, ACTIVE_STATUS VARCHAR2(1 BYTE))";

	public static final String DROP_GDPR_PROCESS_REQUEST_MSTR_TABLE = "DROP TABLE GDPR_PROCESS_REQUEST_MSTR";

	public static final String CREATE_GDPR_PROCESS_REQUEST_MSTR_TABLE = "CREATE TABLE GDPR_PROCESS_REQUEST_MSTR("+"REQUEST_ID NUMBER,REPORT_DATE DATE,REPORT_TYPE VARCHAR2(50 BYTE),"
			+ "REQUESTED_USER VARCHAR2(50 BYTE),REQUEST_STATUS VARCHAR2(50 BYTE),REQUEST_DATE DATE,START_DATE DATE, END_DATE DATE,"
			+ "LAST_UPDATED_TIME TIMESTAMP(6))";

	public static final String DROP_GDPR_MODULE_LVL_RETPEROID_MSTR_TABLE = "DROP TABLE GDPR_MODULE_LVL_RETPEROID_MSTR";

	public static final String CREATE_GDPR_MODULE_LVL_RETPEROID_MSTR_TABLE = "CREATE TABLE GDPR_MODULE_LVL_RETPEROID_MSTR("+"ID VARCHAR2(30 BYTE),MODULE_ID VARCHAR2(30 BYTE),MODULE_OWNER VARCHAR2(255 BYTE),"
			+ "MODULE_RET_YEAR NUMBER(10,0),MODULE_RET_MONTH NUMBER(10,0),MODULE_RET_DAYS NUMBER(10,0),ACTIVE_STATUS CHAR(1 BYTE), CREATED_BY VARCHAR2(200 BYTE),"
			+ "CREATED_DATE DATE,MODIFIED_BY VARCHAR2(200 BYTE),MODIFIED_DATE DATE)";

	public static final String DROP_GDPR_STG_KEY_LIST_TABLE = "DROP TABLE GDPR_STG_KEY_LIST";

	public static final String CREATE_GDPR_STG_KEY_LIST_TABLE = "CREATE TABLE GDPR_STG_KEY_LIST("+"REQUEST_ID NUMBER,MODULE_ID VARCHAR2(50 BYTE),RECORD_ID VARCHAR2(50 BYTE),"
			+ "DISPLAY_ID VARCHAR2(1000 BYTE),DATE_TOBE_CONSIDERED DATE,EXPECTED_DEL_DATE DATE,DEL_EXEC_DATE DATE, DATA_HOLD VARCHAR2(1 BYTE),"
			+ "MAPPED_DATA_HOLD VARCHAR2(500 BYTE),MAX_DATA_HOLD_DATE DATE,SOFT_DELETE VARCHAR2(1 BYTE),STATUS VARCHAR2(100 BYTE), REASON VARCHAR2(1000 BYTE))";

	public static final String DROP_GDPR_REPORT_CYCLE_CONFIG_TABLE = "DROP TABLE GDPR_REPORT_CYCLE_CONFIG";

	public static final String CREATE_GDPR_REPORT_CYCLE_CONFIG_TABLE = "CREATE TABLE GDPR_REPORT_CYCLE_CONFIG("+"LABEL_VALUE VARCHAR2(50 BYTE),KEY_VALUE DATE)";

	

	public static final String SELECT_GDPR_TABLE_LIST = "SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'ADMIN' AND TABLE_NAME LIKE 'GDPR%'";

	public static final String DROP_GDPR_MODULE_LVL_RP_MSTR_SEQ = "DROP SEQUENCE GDPR_MODULE_LVL_RP_MSTR";
	
	public static final String CREATE_GDPR_MODULE_LVL_RP_MSTR_SEQ = "CREATE SEQUENCE GDPR_MODULE_LVL_RP_MSTR START WITH 1";
	
	public static final String DROP_GDPR_PROCESS_REQUEST_MSTR_SEQ = "DROP SEQUENCE GDPR_PROCESS_REQUEST_MSTR_SEQ";
	
	public static final String CREATE_GDPR_PROCESS_REQUEST_MSTR_SEQ = "CREATE SEQUENCE GDPR_PROCESS_REQUEST_MSTR_SEQ START WITH 1";

	
			

			
}
